kind: Deployment
apiVersion: apps/v1
metadata:
  name: leashapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leashapp
  template:
    metadata:
      labels:
        app: leashapp
    spec:
      containers:
        - name: leashapp
          image: abarnash/leashapp:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: leashapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: leashapp
